name: Continuous integration example

on: 
  push:
  pull_request: 

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ macos-latest, windows-latest, ubuntu-latest ]
                java: [ '11', '17', '21']
        name: Java ${{ matrix.java }} sample
        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK ${{ matrix.java }}
              uses: actions/setup-java@v4
              with:
                  distribution: 'adopt'
                  java-version: ${{ matrix.java }}
            - run: mvn test